### ISSUE TITLE
Update for use in python3 and argparse

### ISSUE THREAD

**Issue by WSLUser** [roeyk/nessus-report#1]
Python2 is planned to be no longer supported in 2020 therefore needs to switch to using Python3. I have done this already easily enough myself. Optparse conversion to argparse is a slightly different matter. Optparse is depreciated and has been for years. Edit: Fixed the flatten glob issue but need to address changes to the `string` module. `string.letters` doesn't exist in python3 therefore, requires a substitute but not sure what the best replacement is.

**Comment by WSLUser** [comment]
There are actually more issues converting to python3 than anticipated. Argparse actually seems to be the easier part. Had to go back to scratch and use python-modernize, futurize, and pyupgrade projects to help boost the conversion process. But still not completely comprehensive conversion. Adjusting the string modules use from letters to isalnum is was easy enough but then ran into issues with `decoding str is not supported` and '<' not supported between instances of 'int' and 'str'. Investigating potential fixes. This project was poorly written from what I've investigated so far. Should of been more future proof though understand why it is not.

**Comment by WSLUser** [comment]
Normally a VSCode user but installing Pycharm has revealed a number of issues that may not of been preventing the script from running but certainly showed the inefficiency of it. Even the python2 version seemed like it wasn't quite running everything, just enough that it didn't matter as all the necessary fields that mattered were good. After applying a significant number of auto-corrections from Pycharm and making a couple adjustments, the code has been cleaned up and made far more Pep8 compliant. Still not quite there but may not be worth going down that rabbit hole. Need to test if the encoding issues were fixed when processing a .nessus file. Even if it was, suspect new issues will appear.

**Comment by WSLUser** [comment]
Fixed processing of .nbe and csv. The script now successfully runs in python3 but it fails to get much of the data needed for .nessus. .nbe files aren't even generated anymore so would prefer to drop functionality but will probably leave in case of anything. Doing some digging, discovered the decoding/encoding for .nbe files was done incorrectly and though the script ran, it was likely due to no .nbe files being present.

**Comment by WSLUser** [comment]
Removed .nbe and need only to figure a way of getting a list of strings to be split without changing functionality for RiskFactors. Hopefully will still output reports as normal.

**Comment by roeyk** [comment]
Hey this is wonderful, thanks!!   I would like to get involved in this
again, what do you suggest that I do?

**Comment by WSLUser** [comment]
Yeah I gave up on this as it was mostly used to support learning how to use python  in whatever spare time I had in between other work related projects. I gained a great deal of experience and hardly documented everything I went through, just some small summaries I occasionally entered here in case it ever meant anything. I can update my fork with what I've got but there's issues with it still. I'd still love to be able to use this script but I've been able to get by using the Nessus web UI, which has had some improvements over the past couple years. I will say that I've gotten much better at migrating other scripts at my work that I use as a result of trying to fix this. String conversions appear to be a pain. I was also looking at switching to ElementTree as I had noticed a similar project that had a PR for using ElementTree instead. The current methods are incredibly resource taxing and it appears ElementTree helps reduce that considerably. Odfpy also doesn't update nearly as often from what I've also determined. You can re-open this to work on if you feel like.

**Comment by WSLUser** [comment]
Also sorry for not noticing your reply sooner!
